import { useCallback, useEffect, useState, type FormEvent } from 'react';
import { Activity, Cat, ChevronRight, Pencil, Plus, Trash2, Wifi, WifiOff } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import { feedersApi } from '../services/catfeeder';
import { ApiError } from '../services/api';
import type { Feeder } from '../types';
import { isFeederOnline, formatLastConnection } from '../utils/feederStatus';
import { Button, Modal, Notice, PageState } from '../components/ui';

const icons = ['cat', 'dog', 'rabbit', 'fish', 'paw'];
const REFRESH_INTERVAL_MS = 30_000;

export function FeedersPage() {
  const [feeders, setFeeders] = useState<Feeder[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [editing, setEditing] = useState<Feeder | null>(null); const [deleting, setDeleting] = useState<Feeder | null>(null);
  const load = useCallback(async (showLoading = true) => { if (showLoading) setLoading(true); setError(''); try { setFeeders(await feedersApi.list()); } catch (e) { setError(e instanceof ApiError ? e.message : 'No pudimos cargar tus comederos.'); } finally { if (showLoading) setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]); useEffect(() => { const interval = window.setInterval(() => void load(false), REFRESH_INTERVAL_MS); return () => window.clearInterval(interval); }, [load]);
  if (loading) return <PageState title="Cargando tus comederos…" />;
  return <div className="feeders-view"><section className="page-heading"><div><p className="eyebrow">Tus dispositivos</p><h1>Mis comederos</h1><p>Controlá cada comida sin perder de vista su estado.</p></div><Link className="button" to="/feeders/new"><Plus /> Vincular comedero</Link></section>{error ? <PageState title={error} action={<Button onClick={() => void load()}>Reintentar</Button>} /> : feeders.length === 0 ? <section className="empty-card"><span className="large-icon"><Cat /></span><h2>Todavía no tenés comederos</h2><p>Vinculá el dispositivo con el código que recibiste junto a él.</p><Link className="button" to="/feeders/new"><Plus /> Vincular mi primer comedero</Link></section> : <section className="feeder-grid">{feeders.map((feeder) => <FeederCard key={feeder.feederId} feeder={feeder} onEdit={() => setEditing(feeder)} onDelete={() => setDeleting(feeder)} />)}</section>}{editing && <EditFeeder feeder={editing} onClose={() => setEditing(null)} onDone={() => { setEditing(null); void load(); }} />}{deleting && <UnpairFeeder feeder={deleting} onClose={() => setDeleting(null)} onDone={() => { setDeleting(null); void load(); }} />}</div>;
}

function FeederCard({ feeder, onEdit, onDelete }: { feeder: Feeder; onEdit: () => void; onDelete: () => void }) { const isOnline = isFeederOnline(feeder.lastConnection); return <article className="feeder-card"><div className="feeder-card-top"><span className="pet-icon"><Cat /></span><span className={`status ${isOnline ? 'online' : 'offline'}`}>{isOnline ? <Wifi /> : <WifiOff />}{isOnline ? 'En línea' : 'Sin conexión'}</span></div><h2>{feeder.feederName}</h2><p className="muted">ID: {feeder.feederId}</p><div className="motor-line"><Activity /> <span>Motor: <b>{feeder.motorInfo?.motorState ? 'Alimentando' : 'En espera'}</b></span></div><p className="muted">Última conexión: {formatLastConnection(feeder.lastConnection)}</p><footer><Link className="manage-link" to={`/feeders/${encodeURIComponent(feeder.feederId)}`}><span>Administrar comedero</span> <ChevronRight /></Link><div className="card-actions"><button className="icon-button" onClick={onEdit} aria-label={`Editar ${feeder.feederName}`}><Pencil /></button><button className="icon-button danger" onClick={onDelete} aria-label={`Desvincular ${feeder.feederName}`}><Trash2 /></button></div></footer></article>; }

export function PairFeederPage() { const navigate = useNavigate(); const [credential, setCredential] = useState(''); const [mode, setMode] = useState<'code' | 'token'>('code'); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); async function submit(e: FormEvent) { e.preventDefault(); const value = credential.trim(); if (!value) return setError('Ingresá el código o token de vinculación.'); setLoading(true); setError(''); try { await feedersApi.pair(mode === 'code' ? { pairingCode: value.toUpperCase() } : { pairingToken: value }); navigate('/feeders'); } catch (err) { setError(err instanceof ApiError ? err.message : 'No pudimos vincular el dispositivo.'); } finally { setLoading(false); } } return <section className="form-page"><Link className="back-link" to="/feeders">← Volver a mis comederos</Link><div className="form-card"><span className="large-icon"><Plus /></span><h1>Vincular un comedero</h1><p>Usá la credencial segura incluida con tu dispositivo.</p><div className="segmented"><button className={mode === 'code' ? 'active' : ''} onClick={() => setMode('code')}>Código de 8 caracteres</button><button className={mode === 'token' ? 'active' : ''} onClick={() => setMode('token')}>Token</button></div><form onSubmit={submit}><label>{mode === 'code' ? 'Código de vinculación' : 'Token de vinculación'}<input value={credential} onChange={(e) => setCredential(e.target.value)} placeholder={mode === 'code' ? 'AB2CD3EF' : 'Token de 64 caracteres'} /></label><Notice message={error} /><Button loading={loading}>Vincular comedero</Button></form></div></section>; }

function EditFeeder({ feeder, onClose, onDone }: { feeder: Feeder; onClose: () => void; onDone: () => void }) { const [name, setName] = useState(feeder.feederName); const [logo, setLogo] = useState(feeder.feederLogo || 'cat'); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); async function submit(e: FormEvent) { e.preventDefault(); if (!name.trim()) return setError('Ingresá un nombre para el comedero.'); setLoading(true); try { await feedersApi.edit({ feederId: feeder.feederId, feederName: name.trim(), feederLogo: logo }); onDone(); } catch (err) { setError(err instanceof ApiError ? err.message : 'No pudimos guardar los cambios.'); } finally { setLoading(false); } } return <Modal title="Editar comedero" onClose={onClose}><form onSubmit={submit}><label>Nombre<input value={name} onChange={(e) => setName(e.target.value)} /></label><label>Ícono<select value={logo} onChange={(e) => setLogo(e.target.value)}>{icons.map((icon) => <option key={icon}>{icon}</option>)}</select></label><Notice message={error} /><div className="modal-actions"><Button loading={loading}>Guardar cambios</Button><Button type="button" className="secondary" onClick={onClose}>Cancelar</Button></div></form></Modal>; }

function UnpairFeeder({ feeder, onClose, onDone }: { feeder: Feeder; onClose: () => void; onDone: () => void }) { const [error, setError] = useState(''); const [loading, setLoading] = useState(false); async function remove() { setLoading(true); try { await feedersApi.unpair(feeder.feederId); onDone(); } catch (err) { setError(err instanceof ApiError ? err.message : 'No pudimos desvincular el comedero.'); } finally { setLoading(false); } } return <Modal title="Desvincular comedero" onClose={onClose}><p>¿Querés desvincular <b>{feeder.feederName}</b>? Va a dejar de aparecer en tu cuenta, pero el dispositivo no se elimina.</p><Notice message={error} /><div className="modal-actions"><Button className="danger-button" loading={loading} onClick={() => void remove()}><Trash2 /> Desvincular</Button><Button className="secondary" onClick={onClose}>Cancelar</Button></div></Modal>; }
